// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCopUzF8bPoHMxVDLYtgUQjACZNZJMA6Hw',
    appId: '1:831779380655:web:32a4f98f693b3c6315a35a',
    messagingSenderId: '831779380655',
    projectId: 'cnuity-9653b',
    authDomain: 'cnuity-9653b.firebaseapp.com',
    storageBucket: 'cnuity-9653b.firebasestorage.app',
    measurementId: 'G-KWPNNQP2VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7zm0KA0dkxtfxeLMxYMaunFnl76wcHUk',
    appId: '1:831779380655:android:0d3b69ca150b098b15a35a',
    messagingSenderId: '831779380655',
    projectId: 'cnuity-9653b',
    storageBucket: 'cnuity-9653b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0zfjpBiy8E7fHKydi_TNJ99BAZS1slA',
    appId: '1:831779380655:ios:8e7c51979aecc84f15a35a',
    messagingSenderId: '831779380655',
    projectId: 'cnuity-9653b',
    storageBucket: 'cnuity-9653b.firebasestorage.app',
    iosBundleId: 'com.example.cnuity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0zfjpBiy8E7fHKydi_TNJ99BAZS1slA',
    appId: '1:831779380655:ios:8e7c51979aecc84f15a35a',
    messagingSenderId: '831779380655',
    projectId: 'cnuity-9653b',
    storageBucket: 'cnuity-9653b.firebasestorage.app',
    iosBundleId: 'com.example.cnuity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCopUzF8bPoHMxVDLYtgUQjACZNZJMA6Hw',
    appId: '1:831779380655:web:3f73ab5d13f2dde015a35a',
    messagingSenderId: '831779380655',
    projectId: 'cnuity-9653b',
    authDomain: 'cnuity-9653b.firebaseapp.com',
    storageBucket: 'cnuity-9653b.firebasestorage.app',
    measurementId: 'G-PK5XD07Y6V',
  );

}